### ISSUE TITLE
Install locally in linux

### ISSUE THREAD

**Issue by rsantellan** [the3dfxdude/7kaa#109]
Hi, I just found out about this game and I wanted to try it. 
I download the files on my Ubuntu and run:

- ./autogen.sh 
- ./configure
- make

My problem is that if I run make install it want to install globally and I want it to be only for my user. How can I achieve that? 
Thanks in advance.

**Comment by the3dfxdude** [comment]
From the top level source directory:

$ SKDATA=data ./src/7kaa

https://7kfans.com/wiki/index.php/Building_From_Source

**Comment by rsantellan** [comment]
Thank you @the3dfxdude
