### ISSUE TITLE
It's impossible to assassinate an enemy king

### ISSUE THREAD

**Issue by zyrup** [the3dfxdude/7kaa#117]
If a player has placed a spy in a fort where an enemy king resides, the option is revealed to assassinate the king. However, even if the spy has the maximum skill, the assassination will always fail and result in the execution of the spy.
- In this save game I've placed a 100 skill spy with an enemy king in a fort without additional units: [VENU_005.SAV.zip](https://github.com/the3dfxdude/7kaa/files/2770594/VENU_005.SAV.zip)

The assassination success seems to be calculated in `OSPY.cpp` in `Spy::get_assassinate_rating`. If the target unit has the rank of a king, the defending side gets +50 in defending. Maybe this value is too high. I've never been able to assassinate a king despite having tried many times.

**Comment by sraboy** [comment]
Increase your spy's HP or place additional spies in the building to gain a higher attack rating.

<img width="513" alt="king" src="https://user-images.githubusercontent.com/4247887/51351845-8a929680-1a71-11e9-84e4-545775a5d36f.PNG">

**Comment by zyrup** [comment]
Cool. I wonder however if a player is able to find this information. I never found a description of how I can increase the attack rating. I assumed it relies only on the spy skill.

**Comment by sraboy** [comment]
It's in the manual (page 125): https://steamcdn-a.akamaihd.net/steam/apps/450140/manuals/Seven_Kingdoms_Ancient_Adversaries_manual.pdf?t=1458663750. It's a pretty esoteric bit of knowledge though. I only knew it because I'd tinkered with the Spy code.

**Comment by the3dfxdude** [comment]
Well, I guess if it's in the manual, then this is resolved, right?

FYI, the manual is now provided with the game.
