### ISSUE TITLE
When did it support wildscreen??

### ISSUE THREAD

**Issue by woodgreat** [the3dfxdude/7kaa#119]
When did it support wildscreen?? 16:10,16:9 ration

**Comment by sraboy** [comment]
All the graphics were designed for exactly 800x600 so each one's size and position on-screen is hardcoded. So, after someone redesigns most of the graphics, someone else has to completely rewrite all the menu/window drawing. I've tinkered with this and it's not simple.

**Comment by the3dfxdude** [comment]
It is not implemented and there is no date for this. I have things planned to improve the graphics system. It will come one step at a time.

**Comment by woodgreat** [comment]
thx
