### ISSUE TITLE
War Factory: Clicking on number button in build menu leaves menu.

### ISSUE THREAD

**Issue by Raijinili** [the3dfxdude/7kaa#124]
**Context:** In a War Factory, clicking the build button brings you to a menu with these buttons:
![image](https://user-images.githubusercontent.com/2422807/53587098-815c1580-3b57-11e9-93fc-761c4aa24a8d.png)
There are two buttons shown: the number button, and the bigger button which contains the number button. Clicking on the bigger button queues one catapult and kicks you out to the previous menu.

**Expected:** Clicking on the number button queues one catapult, but leaves you in the build menu.

**Bug:** Clicking on the number button counts as clicking on both buttons: two catapults are queued (one per button), and you're kicked out.

Right-clicking the number button also counts as two clicks.

It also happens with Harbors, but not when training Villagers. (Also, I'm unable to unqueue boat-building in Harbors using right-click, but that's a separate issue.)

---

I'm surprised it hasn't been noticed, since I see war machines in many strats. Could it be just on my computer?

Version 2.15.1 (latest release).

**Comment by sraboy** [comment]
@the3dfxdude Seems related to #122. I don't have this issue with my 23-commits-old build (macOS, master@ a2cafd60f337bfa27c3273a14e32702bec4b2835).

**Comment by the3dfxdude** [comment]
It was noticed. The issue you experience should have been resolved with c768545.
