### ISSUE TITLE
Click Select in Training

### ISSUE THREAD

**Issue by sraboy** [the3dfxdude/7kaa#125]
I encountered an odd issue I wanted to document before I forgot... haven't been able to run this down yet.

When using the training/tutor mode, click "Next Training" and when the in game menu comes up, you'll notice the mouse is dragging the yellow drag-select-rectangle around the screen.

**Comment by the3dfxdude** [comment]
Oh I remember seeing that when testing the new button code. And actually it is indeed due to the new asynchronous method. Should be fixed with 6e4d621ddcb16eadca51296c32a8e120230024fb.
