### ISSUE TITLE
Noun and Adjective Mix-up in ru.po

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#143]
I had a bit of trouble translating something, so these lines might need to be changed:

// TRANSLATORS: Part of "Duration of War Status"
N_("War"),
// TRANSLATORS: Part of "Duration of Tense Status"
N_("Tense"),
// TRANSLATORS: Part of "Duration of Neutral Status"
N_("Neutral"),
// TRANSLATORS: Part of "Duration of Friendly Status"
N_("Friendly"),
// TRANSLATORS: Part of "Duration of Alliance Status"
N_("Alliance")

From ONATIONB.cpp 55 - 64.

In "Duration of Neutral Status," neutral is an adjective, but when displayed as,

Status

Neutral
Neutral
Etc.

they would be considered nouns.

In Russian, one is an adjective, and the other is a noun.

Статус: нейтрален
Нейтральный статус

**Comment by the3dfxdude** [comment]
Closing with commit 81df70e3001122b9fc98a64bc1a2e8fbe6731a59
