### ISSUE TITLE
Date Display in ru.po

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#144]
In Russian, the date is displayed differently than Month Day, Year

It should be Day Month, Year

I would change it myself, but I do not know about "%s %d, %d"

**Comment by the3dfxdude** [comment]
%s is for text.
%d is for numbers.

The code will reference the elements in a fixed order. It is in the order mentioned in the comment, 1) Month, 2) Day, 3) Year. You can rearrange the references, but if it is not in default order, you have to specify a number.

%2$d %1$s, %3$d

Try it out for yourself, and close this issue if it is what you wanted.

**Comment by raz0rknaif** [comment]
Date is now correctly displayed in the Russian translation.
