### ISSUE TITLE
Incorrect help.res Text

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#145]
This may be trivial, but the Help message for REPLYDIP is incorrect.

Short text:

Reply to diplomatic message

Long text:

Click on this colored box to reply this diplomatic message.

It is incorrect in that news messages are considered a diplomatic message. For example, "An Ick Lair has been destroyed" brings up REPLYDIP text when in fact clicking on the news icon centers the screen on the location of the lair, etc.

**Comment by the3dfxdude** [comment]
Ok. This is the improved description.
REPLYDIP
Zoom to activity
Click on this box to reply to the message or to see the location of the event.

**Comment by the3dfxdude** [comment]
Closing with commit 8c42ef0a3b7a33ff26b8bbb4b0db81a289dccfd4
