### ISSUE TITLE
Period Usage after %s's Kingdom%s

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#147]
This may be trivial, but I consider it unsightly if not unseemly.

![image](https://user-images.githubusercontent.com/29286947/57075746-4a1bf900-6cad-11e9-8f7c-3ffe5ca15973.png)

I want to remove the period after the use of a colored box at the end of a sentence.

**Comment by the3dfxdude** [comment]
I'm not going to really bother about period style here.

But, there is no spacing between the box and period. Is this an original game font (English locale)?

**Comment by raz0rknaif** [comment]
I am willing to go into the code and change them. It's the Russian locale.

**Comment by the3dfxdude** [comment]
No. Don't bother.
