### ISSUE TITLE
Increasing the map size

### ISSUE THREAD

**Issue by pietrovismara** [the3dfxdude/7kaa#148]
Has anyone ever experimented with this feature?

I'm trying to change the values in `OWORLDMT.h` and `OWORLD.cpp` (max_x_loc, max_y_loc) but either I break the minimap (it overflows the minimap container) or it segfaults when I launch a new game. Tips on how to do this?

**Comment by sraboy** [comment]
@MicroVirus might have with his "Settings Mod": [forum thread](https://www.7kfans.com/forums/viewtopic.php?f=8&t=840) | [github fork](https://github.com/MicroVirus/7kaa/releases/tag/settings-mod-v0.3)

It's not a simple thing with this code though so I wouldn't expect to find anything close to an easy answer on doing that right now.

**Comment by the3dfxdude** [comment]
This is not supported by the code.
