### ISSUE TITLE
Marking the Ordinal Numbers for Translation

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#151]
I would like to use proper Russian ordinal number abbreviations. 1st is 1-ый in Russian for example. If this is possible, please consider marking the ordinal numbers for translation.

**Comment by the3dfxdude** [comment]
Yes, if it is very limited and not used in a sentence. Can be used for the rank report. Otherwise it gets complicated very quickly and can create issues with gender agreement.

This is now done for the rank report.
