### ISSUE TITLE
Color box displaying incorrectly in Russian on windows

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#152]
On Linux:

![image](https://user-images.githubusercontent.com/29286947/59977800-5cbefa00-959b-11e9-973a-6f86a650a762.png)

On Windows 10:

![image](https://user-images.githubusercontent.com/29286947/59977817-7bbd8c00-959b-11e9-9942-ca6a27ade0ad.png)

**Comment by raz0rknaif** [comment]
I am assuming I need to config win 10 to display non Unicode text to display the color box properly on windows.

**Comment by the3dfxdude** [comment]
The boxes should be inserted directly. It should not depend on the locale.

**Comment by the3dfxdude** [comment]
It might be a bug on Windows generally. Saw something like it just now.

**Comment by the3dfxdude** [comment]
Fixed with commit 05249b9fcdb5e6738a387f81ab8cbcd26be8ff58

**Comment by raz0rknaif** [comment]
![image](https://user-images.githubusercontent.com/29286947/60024214-02866d80-965d-11e9-911d-0a7f0d1ac3e3.png)

FYI (not sure if this is normal) but there is duplicate color boxes in a string with the dev version.

**Comment by the3dfxdude** [comment]
A fix will be pushed for that soon.
