### ISSUE TITLE
Garbled text in Spanish localization

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#153]
![image](https://user-images.githubusercontent.com/29286947/59978658-508b6a80-95a4-11e9-8ffc-3ceb5863764a.png)

**Comment by raz0rknaif** [comment]
This i probably not an issue. It is present in the German localization as well. I am guessing there isn't enough space for the text, and there is over lap. Yet, I didn't have enough space for the Russian text in this context but do not remember overlap.

**Comment by the3dfxdude** [comment]
Yup it's probably just an overflow.

**Comment by raz0rknaif** [comment]
And again, not about the Spanish localization, but is it possible to adjust these buttons? (Next training and quit training).

![image](https://user-images.githubusercontent.com/29286947/61073970-317e3c80-a3dc-11e9-842f-c7edcdbc2594.png)

**Comment by lennyhans** [comment]
A little late, but notices that @the3dfxdude mention the scroll, I didn't check it out yet, is that what you mean @raz0rknaif? [Scroll commit](https://github.com/the3dfxdude/7kaa/commit/0a79c359df834237059e99118fc1b86700ae1c91)

**Comment by the3dfxdude** [comment]
This is not yet addressed.

**Comment by the3dfxdude** [comment]
These have been addressed to the best we can at this time.

In the first item mentioned, there is simply not enough room to display the spanish message. It would be best to condense the message.
