### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#156]
I have gotten a floating point exception twice now. I didn't report it the first time because I was unable to reproduce it. It occurs when I am in observer mode with 9 speed and exit to main menu.

**Comment by raz0rknaif** [comment]
Thread 1 "7kaa" received signal SIGFPE, Arithmetic exception.
0x0000555555568c0e in Nation::process_action (this=this@entry=0x555558740720, 
    priorityActionRecno=4, processActionMode=processActionMode@entry=0)
    at OAI_ACT.cpp:61
warning: Source file is more recent than executable.
61		int maxSessionProcessCount = 70 / nation_array.nation_count / MAX(divider,1);
(gdb) bt
#0  0x0000555555568c0e in Nation::process_action (
    this=this@entry=0x555558740720, priorityActionRecno=4, 
    processActionMode=processActionMode@entry=0) at OAI_ACT.cpp:61
#1  0x00005555555692af in Nation::add_action (this=0x555558740720, 
    actionNode=actionNode@entry=0x555558741c10, 
    immediateProcess=immediateProcess@entry=1) at OAI_ACT.cpp:379
#2  0x0000555555569849 in Nation::auto_next_action (
    this=this@entry=0x555558740720, actionNode=actionNode@entry=0x555558741c10)
    at OAI_ACT.cpp:732
#3  0x0000555555569928 in Nation::action_finished (this=0x555558740720, 
    aiActionId=<optimized out>, unitRecno=<optimized out>, 
    actionFailure=actionFailure@entry=1) at OAI_ACT.cpp:632
#4  0x0000555555569a10 in Nation::action_failure (this=<optimized out>, 
    aiActionId=<optimized out>, unitRecno=<optimized out>) at OAI_ACT.cpp:667
#5  0x000055555564cd36 in Unit::resign (this=this@entry=0x555558cca0d0, 
    remoteAction=remoteAction@entry=3) at OUNIT.cpp:2357
#6  0x000055555564e1ff in Unit::think_betray (this=0x555558cca0d0)
    at OUNIT.cpp:1371
#7  0x00005555555f1b59 in NationBase::deinit_all_unit (
    this=this@entry=0x555558740720) at ONATIONB.cpp:386
#8  0x00005555555f1ca8 in NationBase::deinit (this=this@entry=0x555558740720)
    at ONATIONB.cpp:257
#9  0x00005555555731b9 in Nation::deinit (this=0x555558740720)
---Type <return> to continue, or q <return> to quit---
    at OAI_MAIN.cpp:90
#10 0x00005555555f13b0 in NationArray::del_nation (
    this=this@entry=0x5555558f85e0 <nation_array>, recNo=recNo@entry=2)
    at ONATIONA.cpp:274
#11 0x00005555555f14d0 in NationArray::deinit (
    this=0x5555558f85e0 <nation_array>) at ONATIONA.cpp:96
#12 0x00005555555af12d in Game::deinit (this=0x5555558f71e0 <game>, 
    loadGameCall=0) at OGAME.cpp:258
#13 0x00005555555af355 in Game::deinit (this=this@entry=0x5555558f71e0 <game>, 
    loadGameCall=loadGameCall@entry=0) at OGAME.cpp:243
#14 0x00005555555c0159 in Game::single_player_menu (this=0x5555558f71e0 <game>)
    at OGAMMAIN.cpp:626
#15 0x00005555555c08ad in Game::run_main_menu_option (
    this=this@entry=0x5555558f71e0 <game>, optionId=optionId@entry=1)
    at OGAMMAIN.cpp:306
#16 0x00005555555c0d32 in Game::main_menu (this=0x5555558f71e0 <game>)
    at OGAMMAIN.cpp:256
#17 0x0000555555565c1c in main (argc=1, argv=0x7fffffffe038) at AM.cpp:387
(gdb)

**Comment by the3dfxdude** [comment]
This is not due to the game speed. This is due to the clean up code in a fairly untested observer mode doing something that's completely unneeded. But because of interdependencies I think fixing it without proper test harnesses is more trouble than this is worth right now. If I do a point fix, who knows what other bugs this triggers later as execution is allowed, because remember it's not supposed to be here and never has run through this, and then fixing any more things it uncovers is the same thing again. So proper test harnesses it is, but this one is not a priority due to where it is.

**Comment by the3dfxdude** [comment]
This is actually happening generally in exit, given the right scenario. So I fixed it in d0f25397e099ab826aff8291a8bc33c33b4bd911
