### ISSUE TITLE
Extra commas in Russian translation

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#159]
![image](https://user-images.githubusercontent.com/29286947/60239791-7f3f6480-9874-11e9-81ba-21c0d1ee77a7.png)

I've seen this in the Russian localization for some time, and noticed it isn't present in the Spanish and German localizations.

**Comment by the3dfxdude** [comment]
Fixed by 439581636b1ab49fd63bd2a05e79685a5778efa2
