### ISSUE TITLE
Corrupted ru.po after editing

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#160]
![image](https://user-images.githubusercontent.com/29286947/60318050-1e2c9500-9937-11e9-98de-749b303cbc5c.png)

Not sure if the is a downstream or upstream issue, but this has never happened before. I am hoping to resolve this issue for translator's benefit. Same issue with Poedit.

**Comment by the3dfxdude** [comment]
This is not a game bug?

bash-4.3$ file po/ru.po
po/ru.po: GNU gettext message catalogue, UTF-8 Unicode text

**Comment by raz0rknaif** [comment]
Not a game bug, but I am unable to start working on ru.po without getting this message afterwards. My friend who did a good job previously has time in the coming two weeks to work on it, and I am worried she will run into trouble editing the file. I get this running $ iconv ru.po
#
#  <>, YEAR,iconv: illegal input sequence at position 14

I don't know how to fix this.

**Comment by raz0rknaif** [comment]
I'm closing this as I am now able to edit ru.po without such message appearing.
