### ISSUE TITLE
Strings not being trasnlated

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#161]
I clearly have the string translated in the po file: "матрона Роккены была повержен."

yet it is displayed in English.

![image](https://user-images.githubusercontent.com/29286947/60493682-fd37ad00-9c72-11e9-9e6d-41ed9be77525.png)

**Comment by raz0rknaif** [comment]
Same with the lairs: "Логово Сауродины"

![image](https://user-images.githubusercontent.com/29286947/60494117-cca44300-9c73-11e9-85ff-157d975fd526.png)

**Comment by the3dfxdude** [comment]
What OS is this?

If you have correctly entered the messages, then check which characters are not directly fulfilled by iso-8859-5 plus transliteration. I could not spot any problem characters. If there are any problem characters, then the default behavior is not to return the message, which you get the source message instead.

If you want to find the missing characters, you can add "//IGNORE" to the iconv_open in LocaleRes.cpp. This will force iconv to return whatever can be converted, minus the characters that don't work, so it will simply look mangled if it is a codeset conversion issue.

**Comment by raz0rknaif** [comment]
I am on Linux.

I don't see any problematic characters. I do know I was copying from a Russian dictionary that had accent marks, but I removed those.

I'm sorry. I do not know how to comment out iconv_open.

**Comment by the3dfxdude** [comment]
In LocaleRes.cpp, around line 112, you add this:
        String tocode(codeset);
        tocode += "//TRANSLIT";
        tocode += "//IGNORE";
        cd = iconv_open(tocode, "");

Then see what happens.

**Comment by raz0rknaif** [comment]
Nothing happened.

**Comment by the3dfxdude** [comment]
The problem was when I expanded many messages, all the messages became fuzzy. I correctly extracted the messages, but dropped the call to gettext, meaning it would not lookup the message anymore in the code. I could not test this since the ru database had to be updated anyway to look up the message again. I correctly all that I could see and tested with your pull. Please continue testing.
