### ISSUE TITLE
Weird characters and incorrect kingdom names in messages

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [the3dfxdude/7kaa#164]
Hello!

I've downloaded the latest version of 7kaa (2.15.2 on windows 7) and played a few scenarios, but I've spotted a rather irritating bug. There are weird characters showing up for kingdom names inside messages, that I get from other kingdoms. For example single `+` and `'` characters and sets of dots ranging from `...` to `......`.

Another issue is that every time an NPC wants me to declare war or join on a trade embargo on another NPC, it will incorrectly writing itself as a target. For example `X requests that you declare war on X`.

I'll attach a few screenshots to illustrate the issue.

![7kaa bug embargo message](https://user-images.githubusercontent.com/2386064/60740562-877b5c00-9f66-11e9-8de9-7a44c9b761a1.png)
![7kaa bug weir kingdom name characters plus apostrophe](https://user-images.githubusercontent.com/2386064/60740563-8813f280-9f66-11e9-874c-45a4440d22a1.png)
![7kaa bug weird kingdom name](https://user-images.githubusercontent.com/2386064/60740565-8813f280-9f66-11e9-81a9-d302ad47584e.png)

**Comment by the3dfxdude** [comment]
This is already fixed in commits up to June 27th.

**Comment by meszaros-lajos-gyorgy** [comment]
Okay, so when is the next release? We're still on 2.15.2 since june.
