### ISSUE TITLE
Character info not fully updating for spies, when "drop spy identity" is clicked

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [the3dfxdude/7kaa#165]
Hello!

I don't know, if this has been mentioned before, but there is a very old bug with spies.

When you click the `drop spy identity` button, then the role will correctly change from `Spy` to `Peasant` and the little icon will also vanish from the character sprite, but the spy related UI elements will stay there until the next click on the unit.
![7kaa bug spy 1](https://user-images.githubusercontent.com/2386064/60747596-835f3680-9f86-11e9-831c-866f6caaeb2e.png)
![7kaa bug spy 2](https://user-images.githubusercontent.com/2386064/60747597-83f7cd00-9f86-11e9-8ad9-d022ef0f80c3.png)
![7kaa bug spy 3](https://user-images.githubusercontent.com/2386064/60747598-83f7cd00-9f86-11e9-850c-768c3df39a4d.png)

**Comment by the3dfxdude** [comment]
Fixed with 6a4175646bf60d9eba4c4f76f3166a067ee0179c

**Comment by meszaros-lajos-gyorgy** [comment]
Sweet! Thank you!
