### ISSUE TITLE
Units inside enemy inns will become visible after a while

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [the3dfxdude/7kaa#166]
Hi!

This is yet another very old bug in the game: when you click on an enemy inn, then you don't see the mercenaries inside, as expected. But wait for the inn to update it's list and it will show it's contents.
![7kaa bug enemy inn](https://user-images.githubusercontent.com/2386064/60747658-14cea880-9f87-11e9-8cc1-52a82699838c.png)

**Comment by the3dfxdude** [comment]
Fixed with 24696c49c7ac3c43f7f1f3ea79a6d1b0455c8354

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you!
