### ISSUE TITLE
HELP.RES: Zoom to activity text

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#167]
This text is displaying when the zoom to activity icon isn't present.

**Comment by the3dfxdude** [comment]
I don't know what you mean. Where are you triggering it?

**Comment by raz0rknaif** [comment]
![image](https://user-images.githubusercontent.com/29286947/60918866-f05e1f00-a259-11e9-951d-21a9d4e9ba5b.png)

Both news messages will display the text when hovering the pointer over the location of the icon / no icon.

**Comment by the3dfxdude** [comment]
I think this behavior is to be expected. As soon as the code add a news item with a zoom or deletes the one without, you are holding your mouse still over a help hot spot that now is live, it will show a popup instantly.

Really, I think it's best to think of the popup code as part of learning the game and turn it off when you are done. It's off in multiplayer for a reason.

**Comment by the3dfxdude** [comment]
This is only a slight more annoyance in the news section in single player when pop ups are enabled. The pausing is the real issue. But it happens pretty much anywhere you happen to accidentally place your mouse. I think the solution is to turn it off once you have learned the game.
