### ISSUE TITLE
Text box in 1st tutorial is too small

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#179]
The first message in the first tutorial mission is a bit too long for the text box.

![image](https://user-images.githubusercontent.com/29286947/70434868-05c6b780-1a4b-11ea-8682-0287934e8f1a.png)

**Comment by raz0rknaif** [comment]
It is also present in the Russian version.

![image](https://user-images.githubusercontent.com/29286947/70435964-d5cce380-1a4d-11ea-9e5c-214783bc0e80.png)

**Comment by raz0rknaif** [comment]
The text box for data/resource/tut_text/00007-LOYALTY.txt:29 in the Russian localization is also a bit too small.

![image](https://user-images.githubusercontent.com/29286947/70436656-6b1ca780-1a4f-11ea-9856-2491896922c7.png)

**Comment by the3dfxdude** [comment]
While that text could be split, it's hard to say we can totally prevent an overflow. I added simple scroll ability in 0a79c359df834237059e99118fc1b86700ae1c91
