### ISSUE TITLE
Mobilize Spy Bug

### ISSUE THREAD

**Issue by sraboy** [the3dfxdude/7kaa#182]
A village did not disappear after its only resident was mobilized from the mine they worked in.

Reproduce:
1. Use the attached SAV. You're yellow. The blue mine in the center is the target. The yellow village of yours is providing a single foreign worker to the mine.
2. Capture the mine.
3. Mobilize your spy.

Note the Zulu buildings remaining in the empty blue village, which still shows '1' population even though no one is there.

If you convert your spy back to yellow and place him back into the mine, your own village gets the proper additional population.

[AUTO2.zip](https://github.com/the3dfxdude/7kaa/files/4037580/AUTO2.zip)

**Comment by the3dfxdude** [comment]
Sorry I cannot reproduce with this save file. I'm not sure if this is the save file you based your test.

1. The mine is already captured
2. There is a yellow norman in the mine. I sent him back but makes no difference
3. The blue town is always abandoned no matter how I try to mobilize

What version is this? I made some changes to the mobilization and fixed some issues in 2.15.1/2.15.2, and I see no issues so far.

**Comment by sraboy** [comment]
Oh man, maybe I grabbed the wrong SAV. It might be a release behind... it's on another computer so I'll double check it when I get a chance.

I'll re-open if I can reproduce again on the latest.
