### ISSUE TITLE
2.15.3 random freeze as music track switch or unit acknowledge sound

### ISSUE THREAD

**Issue by meepeek** [the3dfxdude/7kaa#186]
I experience a lot of freezing during game play. Mostly occurred when the music change track or selecting a unit and it voices acknowledge, especially, as I pause/resume, but sometimes it happened on click so I guess the sound loading process should be the problem.

As the process freeze, no input works and the game stopped. I use command line to run but ctrl-c cannot kill the process and after a while gnome display pop-up force quit window so I could end the process.

this is result in the terminal
```
./run-game.sh: line 3:  4973 Killed                  SKDATA=~/game/7kaa-2.15.3/data ~/game/7kaa-2.15.3/src/7kaa
```

I run game on fedora 31 wayland on gnome-shell 8GB of ram. Since fedora has no latest package, I complied the source.

**Comment by meepeek** [comment]
Quite certain that it's the sound. I successfully play through 2.30 hour game, turn off sound and music, and finish without a single freeze.

**Comment by the3dfxdude** [comment]
The "sound loading process" is c++ file i/o, that works on multiple platforms, and I've not witnessed any pausing. But since it happens with any sound, that means it is not related to sound loading at all, since the basic sound effects are preloaded in memory, and you say they cause pausing when those are playing too. This means it's related to creating the streams for playback on the audio device. But again, this works fine on multiple platforms, including linux.

Can you to try another computer?

**Comment by meepeek** [comment]
I don't have another computer for now, but will try on x windows or vm to see if the problem persist.

**Comment by meepeek** [comment]
confirm. only happened on wayland. Experienced on both fedora and ubuntu

**Comment by meepeek** [comment]
since it's not 7kaa bug, I close this issue.

**Comment by the3dfxdude** [comment]
But you said this was an issue when the audio plays? So maybe gnome-shell? How does wayland affect the audio?
https://en.wikipedia.org/wiki/File:Linux_kernel_and_daemons_with_exclusive_access.svg

**Comment by meepeek** [comment]
dunno, it just did. I switched to x and the problems gone. x wayland driver, may be ? I noticed that I start having the problem since I move back from deepin to ubuntu last year to test wayland since many says it ready and gnome put to default.

I'm not an expert, but follow articles, wayland itself not complaint with x so project x wayland to simulate x. It works fine but I recently notice some apps perform slower and some hung up runnig for a long time. e.g. vscode and nodejs

I just guess and it just works. Please try and you will see. Hang up is random in 7kaa but quite often. You shouldn't miss it if you play a whole session.
