### ISSUE TITLE
Fedora package revived

### ISSUE THREAD

**Issue by AndyMender** [the3dfxdude/7kaa#191]
I wasn't quite sure where to post this, since the "official" git URL at https://7kfans.com/git is dead. 7kaa was being packaged for Fedora until recently (Fedora 31, 7kaa version 2.14.7), but the package was orphaned and removed in Fedora 32. 

Long story short, I'm a new Fedora packager and as part of my initial contribution, I decided to revive the 7kaa package. The bug report (together with links to the SPEC file and the src.rpm) is available here: https://bugzilla.redhat.com/show_bug.cgi?id=1837107

The package will most likely be added to Fedora 33 and I'll try to keep it fairly up-to-date.

Pinging @the3dfxdude so this doesn't get lost :).

**Comment by the3dfxdude** [comment]
Hi, is there a request concerning the http git viewer? The git protocol is available.

How was the packager tracking the git page and does it make sense?

**Comment by the3dfxdude** [comment]
BTW, there will probably be a minor patch release real soon, so please keep on top of that. The frequency of releases are low, but they should not be missed.

**Comment by AndyMender** [comment]
> Hi, is there a request concerning the http git viewer? The git protocol is available.

Sadly, I don't know.

> How was the packager tracking the git page and does it make sense?

The project is monitored via anitya: https://release-monitoring.org/project/9557/
Updates are propagated as bug reports: https://bugzilla.redhat.com/show_bug.cgi?id=1701746

> BTW, there will probably be a minor patch release real soon, so please keep on top of that. The frequency of releases are low, but they should not be missed.

Right now I need to bump all of the packages to the latest stable release. I'll try to stay on top of the releases as much as possible.

One thing I forgot to mention is that music was externalized completely, because the previous setup involving an autodownloader script was hackish and the alternative was legally risky due to restrictive licensing of the music files.

**Comment by the3dfxdude** [comment]
> The project is monitored via anitya: https://release-monitoring.org/project/9557/

So based on the checking script, if I stop using github for releases, then this will break again.

> One thing I forgot to mention is that music was externalized completely, because the previous setup involving an autodownloader script was hackish and the alternative was legally risky due to restrictive licensing of the music files.

You don't have to package the music. But there is no alternative other than you include it with the game.

**Comment by AndyMender** [comment]
> So based on the checking script, if I stop using github for releases, then this will break again.

Probably. What is your suggestion? :)

> You don't have to package the music. But there is no alternative other than you include it with the game.

True. I left a note in the package description which can be viewed with `dnf info 7kaa`.

The lastest stable (2.15.4) is almost out in Fedora 31, 32 and Rawhide. I'll do some extra testing today evening to make sure all's well.

**Comment by the3dfxdude** [comment]
I was thinking it would be using RSS, but since it is scraping a specific webpage, I just suggest that you also keep a watch on our website at 7kfans.com just in case.

If you got all that you need, I will then close this.

**Comment by AndyMender** [comment]
> I was thinking it would be using RSS, but since it is scraping a specific webpage, I just suggest that you also keep a watch on our website at 7kfans.com just in case.

I was actually thinking of contributing to this project if/when I find the time.
