### ISSUE TITLE
Manual: Tabs and spaces or just spaces?

### ISSUE THREAD

**Issue by J-Moravec** [the3dfxdude/7kaa#193]
**Originally discussed:** https://github.com/the3dfxdude/7kaa/pull/177

**Problem:**
Previously, there were some whitespace symbols that rendered incorrectly (i.e., rendered as a whitespace in the editor, but not as whitespace in the PDF). This was fixed with search and replace.

In some places, mix of tabs and spaces is used (i.e., tables). This doesn't have an influence on rendering, but it is still an inconsistency.

Changing all tabs into spaces would remove this inconsistency and prevent further mistakes of this kind. All white-space that is not a spacebar would be deemed as an error and removed.

Using (four) spaces instead of tabs is also a more prevalent coding style.

**Solution**
replace all tabs into four spaces, such as: ```sed -i "s/\t/    /g" *.tex```

**Comment by the3dfxdude** [comment]
Merged
