### ISSUE TITLE
Chapter Headings Misaligned

### ISSUE THREAD

**Issue by tmr83** [the3dfxdude/7kaa#202]
Just a couple that I have seen so far. I am not sure if it is system specific. Notice chapter 22 and chapter 20:

![image](https://user-images.githubusercontent.com/80742709/113564491-1a7b7700-95cf-11eb-9fe8-8da9ea4b4b32.png)

![image](https://user-images.githubusercontent.com/80742709/113564589-3f6fea00-95cf-11eb-9b5c-338fe318ddeb.png)

I will try to fix them myself. I am just noting here so that anyone else working on the manual may get to it first.

**Comment by UndescriptDev** [comment]
This was fixed in a local commit with:

```
-	\vspace{-1.5em}
-	\hspace{1.5em}
+	\vspace{-1.69em}
+	\hspace{2.2em}
```
