### ISSUE TITLE
Sectioning and Text Spacing 

### ISSUE THREAD

**Issue by tmr83** [the3dfxdude/7kaa#203]
The spacing looks a bit off.

![image](https://user-images.githubusercontent.com/80742709/113567293-fbcbaf00-95d3-11eb-8057-372e45766b59.png)

I do not remember having the manual spacing like this. I might consider reverting the change. I know the project goal is preservation, but the manual is difficult to preserve 100% because it is so different and coded in LaTeX.

Edit: 

Even spacing for text with and without large fonts looks a bit off:

![image](https://user-images.githubusercontent.com/80742709/113567823-f15de500-95d4-11eb-988e-8672b1eb0a33.png)

Edit2:

And this one shows the sectioning too close together.

![image](https://user-images.githubusercontent.com/80742709/113569002-51558b00-95d7-11eb-910b-4b30b0b8fca5.png)

**Comment by W-Damian** [comment]
For the time being considering I am allowing text not to be \raggedright as per the original manual, I will be removing this code:

```latex
\usepackage[explicit]{titlesec} % For modification of titles
% \titlespacing\command{left}{before}{after}
% spacing: how to read {12pt plus 4pt minus 2pt}
%           12pt is what we would like the spacing to be
%           plus 4pt means that TeX can stretch it by at most 4pt
%           minus 2pt means that TeX can shrink it by at most 2pt
\titlespacing\chapter{0pt}{1.4in}{12pt plus 6pt minus 2pt}
\titlespacing\section{0pt}{12pt plus 4pt minus 2pt}{-4pt plus 6pt minus 2pt}
\titlespacing\subsection{0pt}{12pt plus 4pt minus 2pt}{-4pt plus 6pt minus 2pt}
\titlespacing\subsubsection{0pt}{12pt plus 4pt minus 2pt}{-4pt plus 6pt minus 2pt}
\titleformat%
    {\chapter}% command
    [display]% shape, one of: hang, block, display, runin, leftmargin, rightmargin, drop, wrap, frame
    {\bfseries\Huge}% format
    {\fontsize{40}{40}\selectfont\thechapter}% label
    {0em}% sep
    {
        \vspace{-1.5em}
        \hspace{1.5em}
        \parbox{0.8\textwidth}{
            \raggedright%
            #1%
        }
    }% before-code
    [
        \vspace{0.1em}
        \titlerule
    ]% after-code
```

**Comment by UndescriptDev** [comment]
This issue should be easy enough to fix by adjusting this code:

```
\titlespacing\section{0pt}{12pt plus 4pt minus 2pt}{-4pt plus 6pt minus 2pt}
\titlespacing\subsection{0pt}{12pt plus 4pt minus 2pt}{-4pt plus 6pt minus 2pt}
\titlespacing\subsubsection{0pt}{12pt plus 4pt minus 2pt}{-4pt plus 6pt minus 2pt}
```
But for some reason, I cannot quite get it right at the moment.

**Comment by the3dfxdude** [comment]
I'm not sure if this still needs to be done. Please give an update on this issue on sourceforge or the forum if needed.
