### ISSUE TITLE
A Few Bugs in the Manual

### ISSUE THREAD

**Issue by UndescriptDev** [the3dfxdude/7kaa#206]
A quick note for myself here or anyone else who gets to them first. There are a few bugs in the manual that I have been aware of for some time. It's less a bug from bad coding and more so because of the text and .png inclusion. I previously resorted to in place hacks that would need to be modified due to adding/removing text and resizing the images.

![image](https://user-images.githubusercontent.com/80742709/117668988-11506d80-b16c-11eb-9a73-39e4edf4f45c.png)

![image](https://user-images.githubusercontent.com/80742709/117669068-23321080-b16c-11eb-8be6-e4992cd80b73.png)

![image](https://user-images.githubusercontent.com/80742709/117669205-4230a280-b16c-11eb-828f-88870e058906.png)

![image](https://user-images.githubusercontent.com/80742709/117669308-5eccda80-b16c-11eb-9b0c-66cd1bc46e64.png)

![image](https://user-images.githubusercontent.com/80742709/117669486-8de34c00-b16c-11eb-88e0-b6e2d6eb14f4.png)

![image](https://user-images.githubusercontent.com/80742709/117669593-ae130b00-b16c-11eb-9546-d8690d8453bd.png)

![image](https://user-images.githubusercontent.com/80742709/117669707-d13dba80-b16c-11eb-83bb-11c38189b4d8.png)

![image](https://user-images.githubusercontent.com/80742709/117669886-00542c00-b16d-11eb-88f6-4a6c3971a963.png)

![image](https://user-images.githubusercontent.com/80742709/117669958-119d3880-b16d-11eb-8ebe-bfbbd03e42af.png)

![image](https://user-images.githubusercontent.com/80742709/117670035-24177200-b16d-11eb-9748-803d0ca081e5.png)

**Comment by UndescriptDev** [comment]
Most of these bugs were addressed in pull request #225. There are still bugs in the manual, but I will not keep posting them, so I am closing this issue.

**Comment by the3dfxdude** [comment]
Great work!
