### ISSUE TITLE
Manual: Font Mismatch

### ISSUE THREAD

**Issue by W-Damian** [the3dfxdude/7kaa#211]
These are some examples of a mismatching font. It is the Univers font which is replaceable by  the Universalis font. Looks like it is used for the front page, TOC, chapter titles, sectioning, and index.

![image](https://user-images.githubusercontent.com/80742709/119050299-46886700-b987-11eb-8ed8-0083d55b46d1.png)

![image](https://user-images.githubusercontent.com/80742709/119050352-599b3700-b987-11eb-9e6e-8e4d1775c8e1.png)

![image](https://user-images.githubusercontent.com/80742709/119050385-64ee6280-b987-11eb-8f26-94ce9fb27a89.png)

![image](https://user-images.githubusercontent.com/80742709/119050435-79caf600-b987-11eb-9416-93235934267b.png)

**Comment by W-Damian** [comment]
Here is an example of the chapter titles in all capital letters.

![image](https://user-images.githubusercontent.com/80742709/119263994-f12aa080-bba6-11eb-8d0d-4a73b9552d76.png)

**Comment by W-Damian** [comment]
Here is an example of "Introduction" in the Universalis font and all capital letters:

![image](https://user-images.githubusercontent.com/80742709/119830519-f565ff00-bec1-11eb-9f3b-c37c47f9fc26.png)

Currently, Universalis is loaded as the default (sans seriff?) font with [sfdefault] to be the font for the titlepage, TOC, chapter, sectioning, and index. The accanthis font is still loaded with the intention of being the font for all other text. When \accanthis is declared in the code to change the font, all text after \accanthis{} is changed.

**Comment by W-Damian** [comment]
Compiling with xelatex solves the issue here. I use the fontspec package with accanthis as the main font and universalis as the sans serif font, changing the font style with \textsf{}, but I can only get the fonts to compile from a local directory. In doc, I mkdir fonts/accanthis and fonts/universalis. This benefits the Windows users that may contribute to the manual because I would direct fontspec to /usr/share/texmf-dist on Arch Linux. Font data is circa 500kb. Providing fonts allows for easy installation of other fonts if needed in the future and allows systems to have minimal Latex packages installed.

**Comment by W-Damian** [comment]
Please let me know if providing the fonts is an acceptable solution. Accanthis and Universalis are both GPLv2 with font exceptions. I can make the PR with the dirs, fonts, COPYING, and latexmkrc, but I am wanting to clean a few things up before pushing main.tex and the rest of the .tex files. I can wait for PR #214 to be merged or add them to it if you do not mind so many different changes in that PR.

As for internationalization for the credits, I want to add basic support for it with SIL's Gentium font with the possibility of using other SIL fonts or Computer Modern Unicode in the future if needed, but I do not want to spend to much time on anything that isn't needed yet.

**Comment by the3dfxdude** [comment]
Frankly you don't need to change the COPYING since we are already GPLv2. Importing a font repository or talking about font exceptions really is just for people that are more interested in the complete font generation, and actually we are just end users trying to generate a final doc. If we need the font, we will just include the font file.

Are the fonts found in the standard latex distributions anyway? Why bother keeping a copy? Can you point me to an example of someone else providing these fonts in their document repository? Is there a way we can use an environment variable to deal with distribution specific differences?

**Comment by W-Damian** [comment]
Yes. I would prefer not to. No. Yes with TEXMFDIST, but it's use in the document is too advanced for me at the moment. For now, I will just direct fontspec to /usr/share/texmf-dist/ with a comment about TEXMFDIST.

**Comment by W-Damian** [comment]
Trying to point fontspec to /usr/share/texmf-dist/... failed. But I learned a trick that is working so far. I abandoned trying to use fontspec, and instead, I use \textrm{} and \textsf{} to define whether universalis or accanthis is the font for the text.

**Comment by the3dfxdude** [comment]
We could use autoconf. Are there any macros that can set this variable for us?

**Comment by W-Damian** [comment]
It's probably not necessary. Defining text as either textrm or textrm is working. But I need to sit down for an hour or two and make all the changes in the code before saying ti works completely.

Btw, do you mind if I expand PR #214? I have some good changes like removing \clearpage, changing the 7kfans credits to not differentiate among the roles and define it as volunteering, and switching from \textgoth{} to \textswab{}.

**Comment by the3dfxdude** [comment]
Alright, if you have something figured out. Yes you can expand the PR. Although, I can always just pull it directly from whatever branch you do all your work in. Github pull requests just seem to be electronic tickets, and don't really do anything from my perspective. Just send me a note.

**Comment by W-Damian** [comment]
Do you mind if I switch to e-mail submissions instead of using Github? I do not have a source code base or other project needing contributors, so I do not need a Github account.

**Comment by the3dfxdude** [comment]
Email is fine if you are dealing with small source code changes, and you can just attach the changes. But it helps to have git hosting, to share alot of files, or larger files. I just need to know the git url and the branch name, and that really forms the basis of a pull request.

**Comment by W-Damian** [comment]
There is still a couple things to do regarding fonts in the manual, mainly the titlepage and the bolder font on it, but I do not see any use in opening issues about the manual if I am the one who fixes them. For a bug list / todo list, I will be noting them in the docs/README.
