### ISSUE TITLE
Accents look horrible

### ISSUE THREAD

**Issue by jorgesumle** [the3dfxdude/7kaa#220]
![Captura de ecrã no 2021-09-05 00-43-09](https://user-images.githubusercontent.com/14212780/132109705-d5832a7b-e7d8-4995-a527-782d9101db9a.png)

Letters with accents are down a bit compared to others. I don't know if it's just a matter of using another font for the Spanish translation.

**Comment by the3dfxdude** [comment]
Yes, that is the original font. We do have a new one already in the game that we can use here. See for Polish for example.

**Comment by jorgesumle** [comment]
![Captura de ecrã no 2021-09-06 00-23-02](https://user-images.githubusercontent.com/14212780/132143037-6e0e542c-28eb-48f4-abc3-1d7dd96b00ce.png)

For Esperanto characters with diacritical marks (ĉ, ĝ, ĥ, ĵ, ŝ) it shows a question mark (?).

> We do have a new one already in the game that we can use here.

Where is it defined? Maybe the Polish font works better for Spanish and Esperanto.

**Comment by the3dfxdude** [comment]
Thanks for the information. We may need a special char set then, so let me look at it.

**Comment by the3dfxdude** [comment]
Polish uses iso-8859-2, and Esperanto is iso-8859-3. So I am working on generating fonts.

**Comment by the3dfxdude** [comment]
It's hard to make bitmap fonts look pretty when derived from a TTF font and low resolution, but there you go:
https://github.com/the3dfxdude/7kaa/commit/860d77c60d03b79ea38d22efbe05b5a6f0051a26
