### ISSUE TITLE
Crash running 7kaa with Gnome on Xorg

### ISSUE THREAD

**Issue by UndescriptDev** [the3dfxdude/7kaa#223]
Hi,

I needed to log into my system with gnome on xorg today instead of wayland, and I decided to run 7kaa. It crashes every time. Here is the bt:

Program terminated with signal SIGABRT, Aborted.
#0  0x00007fe826265d22 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fe825982780 (LWP 19550))]
(gdb) bt
#0  0x00007fe826265d22 in raise () from /usr/lib/libc.so.6
#1  0x00007fe82624f862 in abort () from /usr/lib/libc.so.6
#2  0x00007fe8262a7d28 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007fe8262af92a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007fe8262b11bc in _int_free () from /usr/lib/libc.so.6
#5  0x00007fe8262b49e8 in free () from /usr/lib/libc.so.6
#6  0x0000563404acf062 in Font::deinit (this=0x563404c47140 <font_std>)
    at OFONT.cpp:232
#7  0x0000563404b66e18 in Sys::deinit_objects (this=<optimized out>)
    at OSYS.cpp:473
#8  0x0000563404b699af in Sys::deinit (this=this@entry=0x563404c48880 <sys>)
    at OSYS.cpp:251
#9  0x0000563404b69a88 in Sys::deinit (this=0x563404c48880 <sys>)
    at OSYS.cpp:195
#10 Sys::~Sys (this=0x563404c48880 <sys>, __in_chrg=<optimized out>)
    at OSYS.cpp:194
#11 0x00007fe8262684a7 in __run_exit_handlers () from /usr/lib/libc.so.6
#12 0x00007fe82626864e in exit () from /usr/lib/libc.so.6
#13 0x00007fe8252a6822 in _XDefaultIOError () from /usr/lib/libX11.so.6
#14 0x00007fe8252a6b2f in _XIOError () from /usr/lib/libX11.so.6
#15 0x00007fe8252a41a7 in _XEventsQueued () from /usr/lib/libX11.so.6
#16 0x00007fe825285bcb in XFlush () from /usr/lib/libX11.so.6
#17 0x00007fe826a7a4ed in ?? () from /usr/lib/libSDL2-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00007fe826a7c52c in ?? () from /usr/lib/libSDL2-2.0.so.0
#19 0x00007fe8269d3c0e in ?? () from /usr/lib/libSDL2-2.0.so.0
#20 0x00007fe8269d3d95 in ?? () from /usr/lib/libSDL2-2.0.so.0
#21 0x0000563404bc10b8 in Vga::handle_messages (this=this@entry=0x563404c49680 <vga>) at OVGA.cpp:361
#22 0x0000563404b69aca in Sys::yield (this=0x563404c48880 <sys>) at OSYS.cpp:1180
#23 0x0000563404b69c95 in Sys::yield (this=this@entry=0x563404c48880 <sys>) at OSYS.cpp:1228
#24 0x0000563404af83c4 in Game::main_menu (this=0x563404c42b00 <game>) at OGAMMAIN.cpp:225
#25 0x0000563404a989a0 in main (argc=1, argv=0x7ffc58ca5018) at AM.cpp:368

**Comment by UndescriptDev** [comment]
Here is the backtrace after compiling the dev version:

Program terminated with signal SIGABRT, Aborted.
#0  0x00007f70068eed22 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f700600b780 (LWP 22946))]
(gdb) bt
#0  0x00007f70068eed22 in raise () from /usr/lib/libc.so.6
#1  0x00007f70068d8862 in abort () from /usr/lib/libc.so.6
#2  0x00007f7006930d28 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f700693892a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007f700693a1bc in _int_free () from /usr/lib/libc.so.6
#5  0x00007f700693d9e8 in free () from /usr/lib/libc.so.6
#6  0x000055c1bb2b6252 in Font::deinit (this=0x55c1bb42e180 <font_std>)
    at OFONT.cpp:232
#7  0x000055c1bb34d9a8 in Sys::deinit_objects (this=<optimized out>)
    at OSYS.cpp:473
#8  0x000055c1bb35054f in Sys::deinit (this=this@entry=0x55c1bb42f8c0 <sys>)
    at OSYS.cpp:251
#9  0x000055c1bb350628 in Sys::deinit (this=0x55c1bb42f8c0 <sys>)
    at OSYS.cpp:195
#10 Sys::~Sys (this=0x55c1bb42f8c0 <sys>, __in_chrg=<optimized out>)
    at OSYS.cpp:194
#11 0x00007f70068f14a7 in __run_exit_handlers () from /usr/lib/libc.so.6
#12 0x00007f70068f164e in exit () from /usr/lib/libc.so.6
#13 0x00007f700592f822 in _XDefaultIOError () from /usr/lib/libX11.so.6
#14 0x00007f700592fb2f in _XIOError () from /usr/lib/libX11.so.6
#15 0x00007f700592d1a7 in _XEventsQueued () from /usr/lib/libX11.so.6
#16 0x00007f700590ebcb in XFlush () from /usr/lib/libX11.so.6
#17 0x00007f70071034ed in ?? () from /usr/lib/libSDL2-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00007f700710552c in ?? () from /usr/lib/libSDL2-2.0.so.0
#19 0x00007f700705cc0e in ?? () from /usr/lib/libSDL2-2.0.so.0
#20 0x00007f700705cd95 in ?? () from /usr/lib/libSDL2-2.0.so.0
#21 0x000055c1bb3a7d08 in Vga::handle_messages (
    this=this@entry=0x55c1bb4306c0 <vga>) at OVGA.cpp:361
#22 0x000055c1bb35066a in Sys::yield (this=0x55c1bb42f8c0 <sys>)
    at OSYS.cpp:1180
#23 0x000055c1bb350835 in Sys::yield (this=this@entry=0x55c1bb42f8c0 <sys>)
    at OSYS.cpp:1228
#24 0x000055c1bb2de568 in Game::single_player_menu (this=0x55c1bb429b40 <game>)
    at OGAMMAIN.cpp:456
#25 0x000055c1bb2df3a5 in Game::run_main_menu_option (
    this=this@entry=0x55c1bb429b40 <game>, optionId=optionId@entry=1)
    at OGAMMAIN.cpp:304
#26 0x000055c1bb2df628 in Game::main_menu (this=0x55c1bb429b40 <game>)
    at OGAMMAIN.cpp:256
#27 0x000055c1bb27f840 in main (argc=1, argv=0x7ffeccf910a8) at AM.cpp:368

**Comment by the3dfxdude** [comment]
Even if it is not 7kaa at fault, knowing more info may help in case there are other people using your OS/environment. I'd rather have the game respond with some message as a fail-safe if I can prevent an outright crash.

You should consider reporting this to your distro upstream. Is this Arch?

**Comment by UndescriptDev** [comment]
I don't know where to start then, and I am not in a hurry to report this to Xorg.

**Comment by the3dfxdude** [comment]
OK, since same versions work on a different machine, will close this. Let me know the ticket you file.
