### ISSUE TITLE
Some kind of issue with the 7kaa window.

### ISSUE THREAD

**Issue by tmr83** [the3dfxdude/7kaa#227]
I am having some kind of issue with the 7kaa window on my system. I am running a fresh install of Arch Linux with Gnome3 on Xorg. Maybe it is something else like buggy Gnome3, but 7kaa is the only program that does it.

I tried to report it a while ago, but whenever I tried to take a screenshot, the window refreshed or something like that and went back to normal until moving it again. It doesn't always happen, but I keep seeing it. I finally used ffmpeg to capture my screen, and this is a screenshot of the video because the file is so large.

![Screenshot from 2021-12-25 04-16-41](https://user-images.githubusercontent.com/80742709/147389565-0a3d2cd9-f833-4560-85aa-51f5d6eafac9.png)

And Merry Christmas 🎄

**Comment by the3dfxdude** [comment]
Yes, Merry Christmas.

Windowing systems have to inform the programs that its client area has changed, which in this case, I think you are trying to move the window. If the game window is never obscured by another window or screen border, then the window system can just move the drawing directly in memory. If the window is obscured and parts of it is reexposed, then the window system tells it to redraw.

I am not sure what is being shown, other than you attempted to move the window, and the window system is either locked up or purposely not moving the actual window. This doesn't appear to be a game issue. But I'll think about it.

**Comment by tmr83** [comment]
These pop up into the log after this issue happens:

gnome-shell[888]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x562db436c360] is on because it needs an allocation.
gnome-shell[888]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x562db7563300] is on because it needs an allocation.
gnome-shell[888]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x562db5c1cdb0] is on because it needs an allocation.

I will look into it later.

**Comment by tmr83** [comment]
I tried downgrading sdl2 and even Mesa to the versions in the pacman.log to when I first started seeing this issue, but it wasn't immediately apparent that downgrading fixed or caused the issue.

**Comment by tmr83** [comment]
I can trigger this issue on an older laptop that I do not use anymore because it overheats now that temps outside are almost 100 F. everyday. I do not experience this issue with the laptop currently is use.

**Comment by the3dfxdude** [comment]
A hardware issue? What else could it be?
