### ISSUE TITLE
multiple crashes - windows 11

### ISSUE THREAD

**Issue by watery** [the3dfxdude/7kaa#232]
I installed the game some days ago - v2.15.4p1 - on Windows 11.

I got random freezes, but was always able to "recover" by restarting and loading the latest autosave - I could not find any other information than an "Application hang" in Events Viewer.

Today the game crashes, going back to Windows instantly.

The Windows Event Viewer reports (translated to english):
```
Application name that generated the error: 7kaa.exe, version 2.15.4.0, timestamp: 0x00000000
Module name that generated the error: 7kaa.exe, version: 2.15.4.0, timestamp: 0x00000000
Exception code: 0xc0000005
Error Offset 0x000d54be
Process id that generated the error: 0x5b4
Start time of the application that generated the error: 0x01d836067e45029c
Application path: C:\Program Files (x86)\7kaa\7kaa.exe
Module path: C:\Program Files (x86)\7kaa\7kaa.exe
Event ID: 78bf100d-0f34-49d9-94fb-17f7f3266334
Full package name: 
Application ID related to package: 
```

Restarting the game and the computer didn't help.

I attached my DxDiag info, plus all the game user data; you can refer to savegame `newp_002.sav`: [7kaa.zip](https://github.com/the3dfxdude/7kaa/files/8237543/7kaa.zip)

**Comment by the3dfxdude** [comment]
Thanks for this report. This appears to be a long time issue with the game, now fixed by this commit: bcb690f0c127470c1fe65247ab893c6addb9a160
