### ISSUE TITLE
Losing a scenario marks it as "checked" in the scenario menu

### ISSUE THREAD

**Issue by jsynacek** [the3dfxdude/7kaa#235]
1) Select a scenario that you haven't played yet.
2) Play it and lose (get to the losing screen).
3) Go to the scenario menu - you'll see that it has been checked the same way as if you win.

It should probably be checked with the same "minus" mark as if you don't finish it.

**Comment by lennyhans** [comment]
That does not seems like a design feature.

**Comment by the3dfxdude** [comment]
Thanks for report and fix
