### ISSUE TITLE
select an empty ship then a full one: labels are missing

### ISSUE THREAD

**Issue by watery** [the3dfxdude/7kaa#238]
If you select an empty ship, then one that has units in it, labels about loyalty, hit points etc disappear:

![7kaa-ship-labels](https://user-images.githubusercontent.com/3211180/162588373-0f5085d4-b9db-451f-bfc0-a630da57523d.jpg)

**Comment by the3dfxdude** [comment]
Fixed by this commit 89c92e4be8a2afa5077a38dc57c261c3aae19f5f
