### ISSUE TITLE
Cursor is getting stuck at screen edges

### ISSUE THREAD

**Issue by Zalewa** [the3dfxdude/7kaa#240]
I'm playing in fullscreen. Putting the mouse cursor against the edges of the gameplay window scrolls the map view around, as expected, but the cursor gets stuck there. I must shake the mouse quite a bit in both the scrolling and opposite direction in order to get it unstuck. This seems to happen only in the right or bottom direction. This also happens only in **2.15.5**, doesn't happen in **2.15.4p1**.

**Platform:** MS Windows 10
**Game version:** 2.15.5

**Steps to reproduce:**

1. Ensure the game is in fullscreen.
2. Start a new game.
3. Move the mouse cursor to the right or bottom edge of the screen.
4. It should get stuck now with the game perpetually scrolling in the direction.

**Comment by the3dfxdude** [comment]
Hi Zalewa,

We didn't change the mouse behavior in game. So this is either an SDL or Windows change. Can you take the older SDL dll from here and drop it into the game directory? Tell me if this resolves the issue.

https://libsdl.org/release/SDL2-2.0.9-win32-x86.zip

**Comment by Zalewa** [comment]
Yup, using SDL2 2.0.9 fixes the problem.

**Comment by the3dfxdude** [comment]
Ok. The installer has been rebuilt with the older dll version to help everyone, as that was known to be working. I have not reproduced the issue, so I'd like anyone please provide me with information on what changed in SDL to cause an issue in the game. Please take the discussion on this to the forum thread on 7K version 2.15.5: https://7kfans.com/forums/viewtopic.php?f=18&t=1240&p=9326#p9326
