### ISSUE TITLE
Original scenario's spawn non original nationalities after loading

### ISSUE THREAD

**Issue by jvs3** [the3dfxdude/7kaa#245]
Using version 2.15.5 when starting the scenario Hearts and Minds the nationalities are limited to the original seven as expected. After loading the game the other 3 nationalities spawn as well in the inn. I'm not sure if the other 3 nationalities also spawn as units or villages.

It makes no difference if I load the game from a running game or from the main menu. It also happens in the scenario Seven Forts for Seven Generals.

**Comment by the3dfxdude** [comment]
Yes, many of the new game features will not persist across save and reload. Thanks for pointing this one out. I'll make sure it gets addressed when I am working on that code.

**Comment by the3dfxdude** [comment]
Thank you for reporting the issue. I have reproduced the issue and it is confirmed. New code will be written

Tracking this issue has been moved over to the 7kfans forums, as I am migrating off of github. You are also welcome to visit the sourceforge page.

https://7kfans.com/forums/viewtopic.php?f=13&t=1293
