### ISSUE TITLE
Changelog/comments not reachable for non-logged people

### ISSUE THREAD

**Issue by bmorel** [the3dfxdude/7kaa#246]
Hello.
Opening this bug here since not sure if there's a repo for the website. I only could ask to some search engine to find this repo even. Yes, this bug is clearly misplaced, but I also no dot have a forum account so reporting here is easier to me.

Back to topic: the website says [See changes and comment in the forums](https://7kfans.com/forums/viewtopic.php?f=18&t=1240&p=9326#p9326) but this links requires to be logged in (I tried to play with the URI, with no luck, I assume the thread is closed to visitors), which is not very foreigner friendly.

**Comment by the3dfxdude** [comment]
Fixed

**Comment by bmorel** [comment]
Thanks a lot!
