### ISSUE TITLE
did it support moden monitor? maybe it a good idea to support it

### ISSUE THREAD

**Issue by woodgreat** [the3dfxdude/7kaa#248]
just let more space ,more room ,more...in the center ,NICE ! 1920x1060 ,not just 1360x768 ,NICE !

**Comment by the3dfxdude** [comment]
The game will run on a modern monitor in the higher resolutions. What are you asking for?

**Comment by woodgreat** [comment]
Yes,I just ask this, support high resolution monitor ! thanks

**Comment by woodgreat** [comment]
and,when? : )

**Comment by woodgreat** [comment]
when?

**Comment by the3dfxdude** [comment]
I would like clarification on what you are asking. The game will run on modern monitor resolutions. Previous people object to keeping the true aspect ratio stretching that leaves black bands. You can get rid of the black bands by stretching fully across the screen. See the following link.

https://7kfans.com/forums/viewtopic.php?p=8932#p8932

**Comment by woodgreat** [comment]
I got your meaning ,I wanna ask when,the non-stretch high resolutions solution support came ？but,Now I know it will be later ,thank you

**Comment by the3dfxdude** [comment]
This may come and there have been other people requesting this. Please use the game forum topic here if you continue to have interest:
https://7kfans.com/forums/viewtopic.php?f=20&t=1291

**Comment by woodgreat** [comment]
OK
