### ISSUE TITLE
Incorrect help text appearing

### ISSUE THREAD

**Issue by tmr83** [the3dfxdude/7kaa#251]
I was taking screenshots for updating the graphics used in the manual. While using the hot corner feature of Gnome 3, help text popped up. I didn't even have a spy.

![Screenshot from 2022-08-08 11-08-45](https://user-images.githubusercontent.com/80742709/183464622-f6a16557-d17e-41af-b759-2678a880abf3.png)

**Comment by the3dfxdude** [comment]
Fixed
