### ISSUE TITLE
Unit on small island is unable to reboard ship

### ISSUE THREAD

**Issue by tmr83** [the3dfxdude/7kaa#254]
I'm not sure if this is a bug or not. I ran into this situation one time trying to hide my king after almost being destroyed. As you can see, the ship is close enough to land, but the Persian unit doesn't move.

![7K64](https://user-images.githubusercontent.com/80742709/186287146-e25d0375-fbf4-414f-8913-d94949b7c861.png)

**Comment by watery** [comment]
Looks like that to me. Can you upload the save file? It may help investigating it.

**Comment by the3dfxdude** [comment]
It's the scenario "Not all those who wonder are lost".

Based on the size and where he stands, I don't think that should have been considered a landing point.

**Comment by the3dfxdude** [comment]
Also, it is my understanding that units cannot betray on a ship anyway. So that loyalty situation really doesn't show an issue with intended gameplay.

**Comment by the3dfxdude** [comment]
This is probably fixed here: 0c01b24ffb5b40dac5d8ca2e95b12953044cd165

The loyalty shown by a unit in a ship is the standard unit loyalty, which if it is faked if it is a spy. This is true when stationed at any building or ship. For whatever reason, if the unit is mobile, and it is your spy, you may see your spy's true loyalty then in the side panel when selected. However, in buildings when accessing the spy menu, then you are viewing the spy's true loyalty, as well as in the Espionage report. So the only odd one is the ship. I guess the spy's true loyalty is more important for you... for reasons. So for consistency, there probably should be a spy menu when on a ship, then you can view the actual spy loyalty. When mobile, I don't know what should be shown, but I think it works fine as is.
