### ISSUE TITLE
Feature request: easily train a spy into an additional role

### ISSUE THREAD

**Issue by tmr83** [the3dfxdude/7kaa#255]
It would be nice to be able to click into the spy menu and have the training button available. Currently, one has to train a spy and settle him into a new town to train him.

**Comment by the3dfxdude** [comment]
Thank you for the suggestion. I am not sure if this will be done, but it is a nice idea. Moving tracking on this over to the 7kfans.com forum.
https://7kfans.com/forums/viewtopic.php?f=17&t=1294
