### ISSUE TITLE
If I use Esperanto locale, the program fails

### ISSUE THREAD

**Issue by jorgesumle** [the3dfxdude/7kaa#258]
I don't know if this is a Debian packaging issue. I've reported the bug to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023221

**Comment by the3dfxdude** [comment]
The font is missing in the dist resdata, dropping it from the dist archive. The debian team has to insert the file from the repository and fix the Makefile.am for it to fix it. So they can do that or just close the issue and wait for upstream.

**Comment by the3dfxdude** [comment]
Fixed distribution with this commit: c7cdc161a370939cfd27a409b3433f3a1a042f21
