### ISSUE TITLE
Request: change some in game text to pop up help text

### ISSUE THREAD

**Issue by tmr83** [the3dfxdude/7kaa#260]
I have these images:

![Iautogrant](https://user-images.githubusercontent.com/80742709/211386799-b871b394-1264-44d7-887e-b849ccead6ed.png)

![Iautotax](https://user-images.githubusercontent.com/80742709/211386820-8273ab97-7dca-4926-bf43-844322e2f98f.png)

They are poorly sized for the manual.

![image](https://user-images.githubusercontent.com/80742709/211386959-9d83d577-981b-4c40-a589-ecd4f96ebd72.png)

![image](https://user-images.githubusercontent.com/80742709/211387042-c23e3c08-5953-4ecf-9e83-eb718ab9fb37.png)

Can the text in parenthesis be changed to pop up help text when hovering over the 30-100 buttons?

**Comment by the3dfxdude** [comment]
I guess so. But you can just crop it out of the picture for the manual now. It doesn't have to look 100% like what is in the game. There may be other things that won't match the game manual as the interface becomes more dynamic.

**Comment by the3dfxdude** [comment]
Oh, I am trying to consider the use of a pop up. But maybe not a pop up over the text itself as I think that might not be intuitive. Could be over the buttons instead.

**Comment by the3dfxdude** [comment]
This is a good idea. Migrating suggestion tracking to 7kfans.com forum.
https://7kfans.com/forums/viewtopic.php?f=17&t=1296
