### ISSUE TITLE
AI builds unusable harbor in a small pond

### ISSUE THREAD

**Issue by BileDemon** [the3dfxdude/7kaa#265]
Again, I don't know if this is present in the original game or if this is a specific map generation problem:

In my game the AI managed to build a harbor in a small pond that doesn't seem to have a connection to the ocean. This also seemed to prevent the AI to actually build a usable harbor directed towards the ocean.

Either the AI should be prevented from using very small lakes for seafaring or the map generation has a problem where it doesn't make it clear whether there's a (visible) open connection to the ocean.

![7kaa2](https://user-images.githubusercontent.com/94478594/223371832-af158e25-6523-4d24-bf7e-e575ad933c30.jpg)

**Comment by the3dfxdude** [comment]
If you have the seed number & land mass (unlikely to get from a save file right now though) or the autosave that triggers it, send it over. As far as AI is concerned, it might be possible to prevent this one. As far as building there, I think that it is harmless.

**Comment by BileDemon** [comment]
The seed number is 18071984204 and the land mass is medium.

**Comment by the3dfxdude** [comment]
So I've been looking over the code. It doesn't look like the AI even considers that pond at all. It's more likely that the AI wants to build towards the large body of water, and it selected a spot that looks like a beach tile for the large body and happens to share with a beach to the small body, but because of build rules, it can only be a harbor for the small body. It's going to be really tricky to stop this one. The map is also a good test case for the AI and sea.

**Comment by the3dfxdude** [comment]
Well soon after I updated, I figured it out. It's basically a 1 in a million chance of this happening, because I couldn't quickly trigger it in random test runs. Since I got more interested in the ai behavior, I might as well close on this now.

Fixed by dd3a7f229a00d140086ab00bd8ac9c6be511109d

**Comment by BileDemon** [comment]
This is good news. Thanks for fixing this.

I already suspected that the cause may have been a strange tiling constellation, but I couldn't be sure.
There is also another spot on the same map which is right in the center, that looks perfectly like a land bridge where units could cross to the other side of the map. But they can't go over there. Instead ships sail directly over the land tile, which looks really goofy. It seems it's not so clear which tiles are actually water and which ones are land mass.
