### ISSUE TITLE
Can not compile with Clang 16 - incompatibility with c++17 standard

### ISSUE THREAD

**Issue by Pinkbyte** [the3dfxdude/7kaa#270]
Error during compilation:
OMISC.cpp:611:4: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   register int a,b;

Suggested fix: https://raw.githubusercontent.com/gentoo/gentoo/438973c52e3f7342c5a06cc03dd97de720296bdf/games-strategy/seven-kingdoms/files/seven-kingdoms-2.15.5-c%2B%2B17.patch

**Comment by the3dfxdude** [comment]
Yes, we'll deal with it since the standard is now being enforced. However, we do not support clang in this project. You should use gcc for any package you ship.
