### ISSUE TITLE
Mobilize Workers from Buildings

### ISSUE THREAD

**Issue by sraboy** [the3dfxdude/7kaa#53]
We want a "sortie" option for other buildings so you can quickly empty an entire factory, for example.

OP: https://www.7kfans.com/forums/viewtopic.php?f=17&t=112

**Comment by sraboy** [comment]
Branch: https://github.com/sraboy/7kaa/tree/clean_mobilize_workers
PR: the3dfxdude/7kaa#51

**Comment by the3dfxdude** [comment]
Done with pull #62
