### ISSUE TITLE
Caravans Travel Between Empty Markets Indefinitely

### ISSUE THREAD

**Issue by sraboy** [the3dfxdude/7kaa#57]
Having a notification for the user or some sort of auto-stop would be helpful. We have to be careful to not eliminate user-specified routes too often so the user's not stuck further micromanaging caravans. For example, a market may go empty for a year because fryhtans destroyed a factory and the user just hasn't had a chance to rebuild it yet.

Forum post: https://www.7kfans.com/forums/viewtopic.php?f=13&t=795&start=20#p5558

**Comment by the3dfxdude** [comment]
I have implemented in the Trade Report a way to identify caravan and trade firms that are useless. This is on top of adding trade firms to the Trade Report just recently.

It's not automatic, but opening the report, you can identify what needs attention. If you want, you can clean up more quickly by removing the caravans and closing markets by selecting each one and hitting X.
