### ISSUE TITLE
Expose Market's is_retail_market Flag to Users

### ISSUE THREAD

**Issue by sraboy** [the3dfxdude/7kaa#58]
The AI uses it so users should be able to.

Forum thread: https://www.7kfans.com/forums/viewtopic.php?f=13&t=795

[Initial test implementation diff](https://github.com/sraboy/7kaa/compare/visual_studio...sraboy:market_retail_flag)
[Explanation of test](https://www.7kfans.com/forums/viewtopic.php?f=13&t=795&start=20#p5681)

**Comment by J-Moravec** [comment]
I have just randomly opened issues and ... why was this not merged? It always bothered me that AI could divided their markets into goods and resources and I couldn't. I have searched the game quite a long time to find if there is some trick for it that I just didn't figured out.

I would say its quality of life feature comparable with village population networks.

**Comment by sraboy** [comment]
Primarily because I never continued on it enough to do a PR. I'd forgotten all about it TBH... Maybe I'll get started on it again.

**Comment by the3dfxdude** [comment]
I work on the game in my spare time, and there are things I'm working on before this. Also, some things might seem easy to just do, but I've been around the block so to speak on this game, so I'd like to do it right and that also takes time. I do trust sraboy. He'll probably get to it first and I'll be testing it out when he does it.

**Comment by sraboy** [comment]
@J-Moravec I opened a draft PR (#141) if you're up for contributing. It needs some work and plenty of testing.

**Comment by the3dfxdude** [comment]
Closing request on this commit: 79a65205ae7128feff75a230554a438b54af5f0d
