### ISSUE TITLE
No mouse acceleration in fullscreen (linux)

### ISSUE THREAD

**Issue by cleeus** [the3dfxdude/7kaa#59]
Hi, yesterday I made a trunk build (82d81ed09bc942e30cbb06bceb09f5f8cf77f3b3) and played a bit. I noticed that the mouse was not accelerated as it is in X11/xfce. My native resolution is 1920x1080, compositing is disabled, framerates and game speed was good. Switching the X11 resolution down to 800x600 before starting the game did not help either. This was pretty annoying as I normally have high accel and only move the mouse a few centimeters on the pad. In 7kaa fullscreen I had to cross the full mousepad to cross the screen. I noticed there are a few commits recently that fumbled with sdl mouse input handling.

**Comment by cleeus** [comment]
I dissected the issue. Mouse acceleration stopped working in ca879b2136be922f371c41e6be8cc43dbd68e606 .

**Comment by the3dfxdude** [comment]
Well, to be clear, the mouse problems started with SDL_WINDOW_FULLSCREEN_DESKTOP when adding the stretching capability from SDL2. This affects all platforms the same. The commits you reference was to fix the dead zone problems when running full screen. A code change is not required here to re-enable acceleration. Any of the following will give your acceleration.

* Switch to windowed mode using Alt-Enter
* Turn off mouse grab if in full screen using Alt-G
* Or compile the game with -DMOUSE_ACCEL (original game code that emulates mouse acceleration)

Let me know what you think about this.

**Comment by cleeus** [comment]
I already tried -DMOUSE_ACCEL but that didn't work. I'll try Alt-G.

**Comment by cleeus** [comment]
I tried Alt-G on master/HEAD (82d81ed09bc942e30cbb06bceb09f5f8cf77f3b3) (without -DMOUSE_ACCEL). It doesn't seem to have any effect, neither in windowed mode, nor in fullscreen. Am I right that in windowed-mode the mouse should not leave the window with mouse grabbed? Regardless of how often I press Alt-G, the mouse can leave the window.

**Comment by the3dfxdude** [comment]
I'm sorry, it's Ctrl-G.

**Comment by cleeus** [comment]
Playing without grab-mode re-enables acceleration, but is not really a solution since scrolling in the game doesn't work well.
So, next one: -DMOUSE_ACCEL.... it works :) I took a look at the acceleration function and since a simple factor 2 is not enough for my taste, I put together a smoothly incrementing acceleration function (acceleration factor based on atan of movement-distance). This leads to a nice smooth mouse movement which can even be tuned nicely. The code is at https://github.com/cleeus/7kaa/tree/smooth_mouse_accel
It can be activated with -DSMOOTH_MOUSE_ACCEL and has two constants as tunables (sma_scale and sma_slope). Some comments are in the code.

**Comment by cleeus** [comment]
Btw, here is the diff: https://github.com/the3dfxdude/7kaa/compare/master...cleeus:smooth_mouse_accel

**Comment by the3dfxdude** [comment]
Can you edit mouse.init() and add SDL_SetHint(SDL_HINT_MOUSE_RELATIVE_MODE_WARP, "1") ? Then try without your software accel code, and see if that restores the native OS acceleration.

**Comment by MicroVirus** [comment]
For Windows 10 this hint seems to restore the OS acceleration, which is really really nice. Without it, the in-game mouse just feels really awkward. If this works for both Linux and Windows, I suggest we use the hint and forego manual mouse acceleration code.

**Comment by the3dfxdude** [comment]
This hint works in SDL 2.0.3, but not 2.0.4. Hmmm...

**Comment by the3dfxdude** [comment]
OK-- now ignoring the double counting of events that was clouding my picture of mouse acceleration for a while, I figured out that I did need to enable it earlier before the mouse mode gets set in the Vga class. See 3da7a634cfd1a54a05a237bc36f7bf7c370d905d.
