### ISSUE TITLE
Code Documentation

### ISSUE THREAD

**Issue by sraboy** [the3dfxdude/7kaa#65]
Moving the discussion started [in PR#62](https://github.com/the3dfxdude/7kaa/pull/62#issuecomment-228239178) to its own issue.

In general, the code documentation is a bit inconsistent and is very minimal. There is a wiki but it's not terribly complete. As the code is adjusted and features added, it would be nice to have things well-documented in a user-friendly way.

Moving to a new style could be done piecemeal, where code is simply documented as it's worked on or just as the occasional side-project. @the3dfxdude mentioned SDL's documentation as a good example and I agree. I like that the code has some amount of documentation but isn't littered with long paragraphs; more complex documentation is in the wiki and wiki just links back to each file. Since 7KAA isn't a library, I don't think it even needs to be as comprehensive as SDL's docs but the style is nice.

SDL uses doxygen to generate documentation from the code ([here's an old mailing list thread on it](http://thread.gmane.org/gmane.comp.lib.sdl/58637/focus=58698)) but also has a wiki. I'm not sure if they ever did do any automated pull from doxygen to the wiki but we don't necessarily need that either. Doxygen can generate Markdown which means it could just be copy/pasted into the 7kfans.com wiki as time goes on while still being browseable/searchable text files on GitHub (either in source or automatically moved to the repo's wiki). This would require manual updates if things are changed but it is also pretty simple with minimal overhead.

For reference, [here's an example](https://visualstudiomagazine.com/articles/2013/04/01/documenting-c-apis-with-doxygen.aspx) of Doxygen documentation style for C++ and, for the (unsupported) VS users, [this blog post](http://zamma.co.uk/blog/2015/04/05/integrate-doxygen-with-visual-studio/) covers integration of Doxygen with VS.

Most of the code isn't terribly difficult to understand so maybe we do nothing new with the source and just take care of the wiki. I just figured a discussion would be useful.

**Comment by the3dfxdude** [comment]
I don't want to have issues opened that are discussions. Please take it to the forum if you are looking for ideas. If you want to make a proposal, then please do so. I hope to track things that can really be worked on, as you can see, things move rather slow. If there isn't some kind of plan to work on, it probably will never get done.

**Comment by sraboy** [comment]
Understood and that makes sense. I've got a proposal in mind, mostly duplicating SDL's method but with Markdown auto-generation. I want to actually test it out on both Windows and Linux and see how it looks and implements.

**Comment by the3dfxdude** [comment]
Created a forum topic for discussion:
https://www.7kfans.com/forums/viewtopic.php?f=20&t=850

**Comment by voidstarfire** [comment]
How do we even build this on Mac?

**Comment by the3dfxdude** [comment]
I think I will close this now, since we might be able to support this better in the near future. I'd be happy to incorporate something into the static site generator if proposed. We can support markdown as well.
