### ISSUE TITLE
Spy Revealing Bug (SPOILER)

### ISSUE THREAD

**Issue by the3dfxdude** [the3dfxdude/7kaa#66]
The following bug report is a game play spoiler. If you don't know what this is, then you might want to stop here. If you do know what this is, please continue.

---

When a spy switches colors, and cloaked to an enemy nation, its reported loyalty and target loyalty is fixed between 70 and 90. If a player clicks on such unit, seeing that it switched colors, and looks at the loyalty, it will know that it is a spy because non-spies do not have a fixed loyalty ever.

This is caused by this piece of code in Unit::update_loyalty()

```
   if( spy_recno )      // a spy's loyalty is always >= 70
   {
      if( loyalty < 70 )
         loyalty = 70+misc.random(20);    // initialize it to be a number between 70 and 90

      target_loyalty = loyalty;
      return;
   }
```

The recommendation is to remove it, for two reasons.
1) It is quite detrimental to gameplay, since spies are now so predictable, that they are useless against a human player if they are caught initially mobile.
2) 7K2 also removed the offending code.

**Comment by MicroVirus** [comment]
I might agree with removing it, but only if it is replaced with another gameplay mechanic that will allow you to counter spies.

Spies are very powerful (get one into a fort and pay some cash, and you can take over an entire troop), so there need to be different (more fun?) ways to manage them, else the game, I fear, will become too unbalanced.

**Comment by the3dfxdude** [comment]
If you fear the cheese tactic of sneaking spies into forts, which the AI seems to be a fan of, then I suppose it could get addressed.

How about a random chance for catching a spy sneaking into a fort/firm on orders of the cloaked nation? The spy's skill would be a factor. I am also thinking that the higher population of the nation, the better for the spy to blend in undetected when sneaking around. This might be a good balancing factor to make spying a more appropriate tactic against nations that are already doing well. I will also suggest to make it essentially impossible to enter a fort just manned by a single general and then immediately bribing the general, since that is pretty obvious.

This actually could hurt the AI some, since it highly depends on these, but the AI needs improving anyway. For multiplayer, I think it would make things more interesting as that might make people invest in counter-spying / training / secondary skills in the early game before taking them offensive. And if they really want to, they can now use the announce button with the obvious give-away.

I might bring this over to the forum as suggestions, but I will likely fix the mentioned bug here anyway, since it is fixed in 7k2.

**Comment by MicroVirus** [comment]
My main point is that I fear that changing the way spies work (what you call a bug, what I consider a feature :P) without counter-balancing will leave the game in a broken state. That's why I'd like to see these changes happen together, or at least without too much time in between.
I suspect that 'the AI announces its spies by default' has been a conscious choice by the original developers, for gameplay reasons, because else it would make the game too frustrating.

I do think/agree that changing spies to make them more sneaky can be a change for good, making them more usable and more fun. We just need to do it in the right way.

**Comment by the3dfxdude** [comment]
'The AI announces its spies by default?' No that is not true. It tries a combinations of things.

Why even have announce as an option, if you can tell right away it is a spy? All it has led to is people using sneak 100% of the time and a weaker AI. Couple that that they actually fixed the problem in 7K2, and code-wise, this feature looks like they were simply adjusting the wrong parameter, that should never be touched this way IMO. I'm pretty certain after review.

Note: The loyalty bug affects spies announce or not. So when the AI does announce, it gives everything away immediately. Those two factors clash on design, and so one has to be a bug. Since announce is clearly part of the game, the loyalty is the bug.

Note2: After some time, the loyalty does recover to a corrected level per Kingdom. The other part of the bug is that the loyalty is very high, and constant, which no other mobile unit is like that! The fix makes the loyalty be calculated like any other unit again.

So honestly, this can't be purposeful design. I think this has to be fixed anyway. The AI problems can be addressed. If certain spy actions are overpowered, they are overpowered anyway and need balancing. We'll deal with reports of being overpowered as they come in.

**Comment by jlac1024** [comment]
Yeah the quick way to tell spies was static or _increasing_ loyalty.

If you're going to change it, make counter-spy more immediate, and definitely more powerful than it currently is (seems to be low on how often it catches a spy).

**Comment by the3dfxdude** [comment]
Disabled fake spy loyalty
commit f91336d6d9259b8fc66c10e0b52d686e77129311

After much study, I decided it will be fine to remove the fake spy loyalty. This primarily will help the AI, so that a human player can no longer do simple filtering on the constant loyalty condition. Now you have to think a bit, just like we did when we first played the game.

I did some researching on how bonus units are created, and how the announce works for both spies and bonus units. There are likely subtle differences still between spy and non-spy, and actually, I'm okay with it. If someone finds a clever way to detect a spy, it might make things a bit interesting actually. As it was with the constant loyalty, no one cared about thinking about it since it was such an easy rule, therefore was completely uninteresting.

There are actually still fairly easy pointers to detecting a spy. For one, if you see one sneaking around, you know it is a spy. A bonus unit may seem very random, or even inflated in stats / loyalty. The AI does try to blend in the unit the best it can, even if more normal stats, and also, rebel/betray units, while rare, will likely be collateral damage, since their stats will be much like any typical unit. But at least the randomness can spice things up and be more psychological rather than the monotonous nature it is right now.

As far as play balancing, I feel that spy detection level is reasonable now. Previously, when using announce, it was clearly too easy. Sneaking, while harder to catch in the moment, was also easy to convince yourself with clicking and seeing the constant loyalty. Now announce is harder, since it was supposed to seemingly blend in with bonus units, and sneaking is not really harder to detect, since again, sneaking is a pretty good giveaway if you see it happen.

I could not find a really good way to make entering the fort be a way to detect a spy. For one, if it could be spammed clicked enter-exit and if the game did not track the ordering nation, then all you have to do is put them through a firm multiple times, and you'll find them. So we'd need to track the nation who gave the order whether if it came from the cloaked nation, and check based on that upon entering the firm. That will require some structural changes. We might be able to do this instead at the moment the order is given from a cloaked nation (after all, giving orders directly to a spy should be risky), but I will hold off on it, since I'm not convinced it is needed, and that is more of a game changer.

If any one spying act is imbalanced, (particularly bribe), then nothing here really changes that imbalance. We could address it if we have data to make the case, but I haven't seen data.

Lastly, one thing I do think can be done (my current favorite choice) is since this change affects AI the most, if AI spying becomes much more effective (since it can micro-manage spies quickly), then we can scale back the AI then by reduce the rate of attempted proliferation, or cap the number of spies. The AI creates too many spies right now, and uses them poorly, which could be one reason why the AI seems so stupid (no money -- too many expenditures, including spies). If we simply make it cut back on spies, the AI could seem smarter and less risky to simply imploding, and also not seem so overpowered with all their spies. Besides, I don't think spies will be a huge issue in the end, since a smart human player should be able to deal with most things. So I think minor tweaks to the AI might be okay if really necessary.

Anyhow, if you want to test the game before and after, see the flag. I will try playing the game some to see how things feel more. It will be 1998 all over again :) and that is a good thing.

**Comment by MicroVirus** [comment]
I can agree with your points. If something is unbalanced, then it'll be in the strength of spy actions and in the weakness of counter-spy measures.

I have no idea right now what counter-spying does right now, but it would be nice if you could counter enemy spies in your fort using your own counter-spies. This will stimulate having spies as a human player, which can be a fun gameplay mechanic.

We can evaluate the need for making spy actions a little harder, such as not being able to take immediate action when entering a building (cooldown period), and/or a chance of detection on entering a fort/building, This should make it a bit more fun, because the AI can do its best to sneak in spies, but at the same time the player isn't punished for taking a little while to fill-up forts and other buildings.

**Comment by the3dfxdude** [comment]
> I have no idea right now what counter-spying does right now, but it would be nice if you could counter enemy spies in your fort using your own counter-spies. This will stimulate having spies as a human player, which can be a fun gameplay mechanic.

You can put your spies into your fort to counter-spy. Are you referring to something else? Putting counter-spies into your fort increases the chance of finding a spy alot. In fact, I'm not sure if I remember ever seeing a successful spy attack through a fort when I do this. I don't know the details on counter-spying from the code, but it is pretty effective against AI. The problem with the counter-spying is the micromanagement and cost. Replacing spies killed from battle from your forts, since they are soldiers after all, is a problem, and they tend to be weaker than average unless you spend the time and money...

I might entertain a regenerative mana bar for a spy. Actions will have a certain cost and spy skill could decrease the cost. It is somewhat similar to how a greater being works. But again, simply ideas.

**Comment by MicroVirus** [comment]
Yeah, I was referring to putting your own spies into towns and forts and that I had no idea on what that does. If it's pretty effective, then it's a fun mechanic, and perhaps our goal should be to ease the burden of micromanagement somewhat?
Perhaps we can have a soldier get additional training as a spy inside the fort, perhaps starting at spying 10 or even 0 to penalise w.r.t. training a new recruit from a town and/or make it more expensive if a unit has higher combat level and/or skill level.
Additionally, we could have the town be able to train skilled spies, such that when you click Train -> Spy that you can then select another skill or none, to be able to train a spy with a profession.
