### ISSUE TITLE
Simplify Directory Structure

### ISSUE THREAD

**Issue by the3dfxdude** [the3dfxdude/7kaa#67]
The directory structure is broken down into too many sections, and things still feel out of place, and makes it hard to search across all the directories. This is a proposal to merge the files of most directories in src/ back into src/. Here is the plan:
## Moves

audio/openal/ -> openal/
client/\* -> .
common/\* -> .
file/\* -> .
input/sdl/\* -> .
multiplayer/common/multiplayer.cpp -> enet/multiplayer.cpp
multiplayer/common/(remaining) -> .
video/sdl/\* -> .
video/common/\* -> .
## Deletes

input/none/
video/none/
## Rationale

SDL became a hard requirement after the removal of DirectX. There is no reason to swap it out anymore, and it has plenty of good portable bits that go beyond video/input. The video bits are hard to separate from the code at this time. The input bits are hard to separate from SDL. So all of it really should just remain with the core game code for the time being.

Multiplayer and audio remain a small section of easily identifiable code. They could be replaced again if needed. They can be put in separate directories just in case.

We can structure related classes into their own directories later, but it is unlikely anything will get that much attention.

The plan is to get the done first for 2.14.7.

**Comment by MicroVirus** [comment]
Sounds like a good plan. Directories have their own issues and since the file names are quite good (for most), there is no real need for the bookkeeping.

I guess the original idea was also to try and modularise it a bit for the client/server code, but that doesn't seem to be relevant currently.

**Comment by sraboy** [comment]
I'm late to the party on this one but I wholeheartedly support it. All the extra directories just don't make any sense when the code isn't actually as modular as the directories would imply.

**Comment by the3dfxdude** [comment]
This is now done. MicroVirus, you'll need to update your visual studio project to match.

**Comment by MicroVirus** [comment]
Roger that. Will hopefully get around to doing that today.
