### ISSUE TITLE
Please use standard libuuid

### ISSUE THREAD

**Issue by beberking** [the3dfxdude/7kaa#68]
Dear 7kaa developpers,

I am currently one the maintainers of the 7kaa Debian package. I was wondering whether it is really necessary to copy the external code of libuuid from e2fsprogs. And is it necessary to rename uuid_t to a custom name ?

It would be great if you could use the standard libuuid instead of copying and modifying your own version.  Please see [1] about why it is always better not to ship third party code. For instance, e2fsprogs v1.43.3 is now out, but you based your fork of libuuid on v1.43.1.

If you must include the libuuid code in your source tarball, please provide a way not to use it at compile time and instead use the system libuuid library.

Best regards,
Bertrand Marc

[1] https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code

**Comment by the3dfxdude** [comment]
Sorry, this is not possible. The reason why the lib was integrated directly into the code base was to ensure full portability onto windows machines with stock windows libs and no additional dependencies. The reason why e2fsprogs was used is that it was written in a more portable fashion to windows, and the forked libuuid repository broke some of the original code. So e2fsprogs gave me a simpler starting point, and I made some additional changes to make it seemless.

Also, you got it a bit wrong, I did not start from the libuuid repository at all but extracted from e2fsprogs.
