### ISSUE TITLE
Different savefiles error

### ISSUE THREAD

**Issue by woodgoblin** [the3dfxdude/7kaa#79]
Both machines have Windows 10 Version 1607 (OS build 14393.693)
(One is Pro, the second one is Home)
Whenever we play, then save and try to load the multiplayer game, the following message is displayed:
"You cannot join the game because the multiplayer saved game you selected is different from those of other human players". 

Dates on savefiles are the same. We are now in different timezones, but we tried to change the system time, which was of no use.

Can anyone confirm? I don't quite understand the cause from the sources I've found.

**Comment by the3dfxdude** [comment]
If that happened, then the game desynced before you saved.

If the game desynced due to some game bug, I don't think I will be able to tell just on the save file. However, if the game just barely desynced, or desynced triggered by the save, then maybe I could. Can you send the save files from both machines?

**Comment by woodgoblin** [comment]
Sure, thanks.
It happened several times, even after 10-second games and we saw no desync signs.

The attachment below is our original saves.
[AUTO.zip](https://github.com/the3dfxdude/7kaa/files/785240/AUTO.zip)

**Comment by the3dfxdude** [comment]
It will be hard to debug using an old save since we do not know how far it is desynced. Please upgrade to 2.15.0 and open an issue if there is a desync, since it has sync checking enabled and replay file support. See this post:
https://www.7kfans.com/forums/viewtopic.php?f=20&t=915
