### ISSUE TITLE
7kaa 2.14.7 fails to build on ARM (narrowing conversion of '-1' from 'int' to 'char' inside { })

### ISSUE THREAD

**Issue by akien-mga** [the3dfxdude/7kaa#81]
7kaa 2.14.7 fails to build on Mageia's ARM nodes (armv5tl and armv7hl) with:
```
make[2]: Entering directory '/home/iurt/rpmbuild/BUILD/7kaa-2.14.7/src'
  CXX      OGAMMAIN.o
OGAMMAIN.cpp: In member function 'void Game::multi_player_menu(int, char*)':
OGAMMAIN.cpp:682:2: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
  };
  ^
OGAMMAIN.cpp:682:2: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
Makefile:944: recipe for target 'OGAMMAIN.o' failed
```

Based on this StackOverflow question this kind of narrowing conversion seems to be implementation defined, and apparently raises an error for GCC 5.4.1 on ARM.

There are various occurences of narrowing conversion, I "fixed" them by changing to `signed char`, and it built fine, but I don't know if that's the correct solution: http://svnweb.mageia.org/packages/cauldron/7kaa/current/SOURCES/7kaa-2.14.7-narrowing.patch?view=markup&pathrev=1106869

If you consider it good, I can make a PR with this patch.

**Comment by MicroVirus** [comment]
Possibly related issue: https://github.com/the3dfxdude/7kaa/issues/63

**Comment by the3dfxdude** [comment]
Yes, there is similarity. At least this one is likely one I can test. It would be nice if these distros actually tested the program, because I'm pretty sure the game never has worked on ARM, before GCC was improved. I'll take a look.

**Comment by the3dfxdude** [comment]
Can you instead build with "-fsigned-char"? Also, is there a way to know if -funsigned-char is being forced on in your build chain? Is this something decided by the mageia arm platform? What's the defaults for gcc?

**Comment by akien-mga** [comment]
> It would be nice if these distros actually tested the program, because I'm pretty sure the game never has worked on ARM, before GCC was improved.

Sadly I don't have an ARM board to try it. It could indeed be that it built fine but that the game wouldn't run.

> Also, is there a way to know if -funsigned-char is being forced on in your build chain? Is this something decided by the mageia arm platform? What's the defaults for gcc?

Those are the flags we enforce, for armv5tl:
```
CFLAGS='-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -march=armv5t'
CXXFLAGS='-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -march=armv5t'
FFLAGS='-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -march=armv5t'
LDFLAGS=' -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags'
```
And for armv7hl:
```
CFLAGS='-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16'
CXXFLAGS='-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16'
FFLAGS='-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16'
LDFLAGS=' -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags'
```

I don't think Mageia defines something different from GCC's default here; according to http://blog.cdleary.com/2012/11/arm-chars-are-unsigned-by-default/ it is expected that ARM uses unsigned chars for `char`, so a fix could indeed be to enforce `-fsigned-char` in your buildsystem.

I'll give the option a try and report back.

**Comment by akien-mga** [comment]
I confirm it builds fine on [armv5tl](http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20170605160750.akien.duvel.42719/7kaa-2.14.7-5.mga6/build.0.20170605160812.log) and [armv7hl](http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20170605160750.akien.duvel.42719/7kaa-2.14.7-5.mga6/build.0.20170605160817.log) with `-fsigned-char`.

**Comment by the3dfxdude** [comment]
OK should be fixed by commit aV8gohVie9. I did some quick tests on arm, but did not build the game.
