### ISSUE TITLE
Cann't build `73fadc` commit.

### ISSUE THREAD

**Issue by o01eg** [the3dfxdude/7kaa#86]
Commit 73fadc4c9a9947d67b1f11c62df9187b87f5902c fails to build:

```
make[2]: Leaving directory '/tmp/portage/games-strategy/7kaa-9999/work/7kaa-9999/src'
make[1]: Leaving directory '/tmp/portage/games-strategy/7kaa-9999/work/7kaa-9999/src'
Making all in po
make[1]: Entering directory '/tmp/portage/games-strategy/7kaa-9999/work/7kaa-9999/po'
make 7kaa.pot-update
make[2]: Entering directory '/tmp/portage/games-strategy/7kaa-9999/work/7kaa-9999/po'
make[2]: *** No rule to make target '../src/OGFILEA.cpp', needed by '7kaa.pot-update'.  Stop.
make[2]: Leaving directory '/tmp/portage/games-strategy/7kaa-9999/work/7kaa-9999/po'
make[1]: *** [Makefile:362: 7kaa.pot] Error 2
make[1]: Leaving directory '/tmp/portage/games-strategy/7kaa-9999/work/7kaa-9999/po'
make: *** [Makefile:447: all-recursive] Error 1
```

Previous commit a81b58517310225e1b31b6ce2f90c634c50b1ad6 successfully builds.

**Comment by MicroVirus** [comment]
That's interesting; I always get 7kaa.pot errors, I've been getting them as long as gettext has been introduced. At any rate, OGFILEA.cpp is gone since the refactor.

Is the POTFILES.in automatically (re)generated or does it need to be edited manually?

**Comment by o01eg** [comment]
`POTFILES.in` is edited manually.

**Comment by the3dfxdude** [comment]
I have this fixed in a local commit. I'll push it later. The game itself still gets built, btw.

Also, I'll probably write a script to keep the POTFILES.in up to date, but I might pull .pot generation out of the default Makefile target since pot-update doesn't work really for what we need.

**Comment by the3dfxdude** [comment]
POTFILES.in updated in commit e0f465db18e902c950681fa144058ae2be7cabbaESC
