### ISSUE TITLE
The F11 screenshot function gives blank images

### ISSUE THREAD

**Issue by MicroVirus** [the3dfxdude/7kaa#94]
The screenshot functionality doesn't seem to be working anymore. When I take a screenshot using F11, the BMP files show up as all-white. Tested using windowed mode on Windows 10 with the latest dev version.

I have no idea since when this feature broke and if factors such as fullscreen influence it.

**Comment by the3dfxdude** [comment]
It works here on linux. Windowed and non-windowed. Tested on SDL 2.0.5. The screenshot routine is simply a call to SDL_SaveBMP. Should be pretty easy to narrow down to that.

**Comment by the3dfxdude** [comment]
I've tested this on SDL 2.0.5+ both windows and non-windows. There is no issue found. Sorry, running out of ideas. Maybe it got fixed somewhere.

**Comment by the3dfxdude** [comment]
Not reproducible so closing.
